[package]
name = "ps" 
version = "1.0.0"
authors = ["RAJ"]
description = "A simple and fast port scanning tool for local IPs or CIDR ranges."
license = "MIT"
edition = "2021"


[dependencies]
ipnetwork = "0.18"
